# Setup
title:        iOS Good Reads
tagline:      Самые интересные статьи, новости и видео, связанные с iOS разработкой.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       etolstoy
  url:        http://etolstoy.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown